# Use root/example as user/password credentials
version: '3.1'

networks:
  shopping-network:
    driver: bridge

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      # TZ: Asia/Seoul
      # TZ: UTC
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/mysql
    ports:
      - 6000:3306

    networks:
      - shopping-network

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis_boot
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
